onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_cpu/cpu_i/data_mem2cpu
add wave -noupdate /tb_cpu/memory_i/rd_en
add wave -noupdate /tb_cpu/memory_i/wr_en
add wave -noupdate /tb_cpu/memory_i/din
add wave -noupdate /tb_cpu/memory_i/dout
add wave -noupdate /tb_cpu/memory_i/addr
add wave -noupdate /tb_cpu/cpu_i/data_cpu2mem
add wave -noupdate /tb_cpu/cpu_i/addr_cpu2mem
add wave -noupdate /tb_cpu/cpu_i/clk
add wave -noupdate /tb_cpu/cpu_i/rst
add wave -noupdate /tb_cpu/cpu_i/mem_en
add wave -noupdate /tb_cpu/cpu_i/mem_rd_en
add wave -noupdate /tb_cpu/cpu_i/mem_wr_en
add wave -noupdate /tb_cpu/cpu_i/w_1_f_d_mem2reg_sel
add wave -noupdate /tb_cpu/cpu_i/w_1_f_d_reg_wr_en
add wave -noupdate /tb_cpu/cpu_i/w_1_e_f_alu_zero
add wave -noupdate /tb_cpu/cpu_i/w_1_e_f_mem_addr_sel
add wave -noupdate /tb_cpu/cpu_i/w_1_e_f_reg_wr_en
add wave -noupdate /tb_cpu/cpu_i/w_1_e_f_mem2reg_sel
add wave -noupdate /tb_cpu/cpu_i/w_1_e_f_mem_wr_en
add wave -noupdate /tb_cpu/cpu_i/w_1_e_f_branch
add wave -noupdate /tb_cpu/cpu_i/w_1_d_r_rd1_addr_sel
add wave -noupdate /tb_cpu/cpu_i/w_1_d_r_rd2_addr_sel
add wave -noupdate /tb_cpu/cpu_i/w_1_d_r_alu_in2_sel
add wave -noupdate /tb_cpu/cpu_i/w_1_d_r_branch
add wave -noupdate /tb_cpu/cpu_i/w_1_d_r_mem_wr_en
add wave -noupdate /tb_cpu/cpu_i/w_1_d_r_mem2reg_sel
add wave -noupdate /tb_cpu/cpu_i/w_1_d_r_reg_wr_en
add wave -noupdate /tb_cpu/cpu_i/w_1_d_r_mem_addr_sel
add wave -noupdate /tb_cpu/cpu_i/w_1_d_r_reg_wr_en_2
add wave -noupdate /tb_cpu/cpu_i/w_1_r_e_alu_in2_sel
add wave -noupdate /tb_cpu/cpu_i/w_1_r_e_branch
add wave -noupdate /tb_cpu/cpu_i/w_1_r_e_mem_wr_en
add wave -noupdate /tb_cpu/cpu_i/w_1_r_e_mem2reg_sel
add wave -noupdate /tb_cpu/cpu_i/w_1_r_e_reg_wr_en
add wave -noupdate /tb_cpu/cpu_i/w_1_r_e_mem_addr_sel
add wave -noupdate /tb_cpu/cpu_i/n2
add wave -noupdate /tb_cpu/cpu_i/n4
add wave -noupdate /tb_cpu/cpu_i/SYNOPSYS_UNCONNECTED_1
add wave -noupdate /tb_cpu/cpu_i/SYNOPSYS_UNCONNECTED_2
add wave -noupdate /tb_cpu/cpu_i/SYNOPSYS_UNCONNECTED_3
add wave -noupdate /tb_cpu/cpu_i/SYNOPSYS_UNCONNECTED_4
add wave -noupdate /tb_cpu/cpu_i/SYNOPSYS_UNCONNECTED_5
add wave -noupdate /tb_cpu/cpu_i/SYNOPSYS_UNCONNECTED_6
add wave -noupdate /tb_cpu/cpu_i/SYNOPSYS_UNCONNECTED_7
add wave -noupdate /tb_cpu/cpu_i/SYNOPSYS_UNCONNECTED_8
add wave -noupdate /tb_cpu/cpu_i/SYNOPSYS_UNCONNECTED_9
add wave -noupdate /tb_cpu/cpu_i/SYNOPSYS_UNCONNECTED_10
add wave -noupdate /tb_cpu/cpu_i/w_16_f_d_data_mem2cpu
add wave -noupdate /tb_cpu/cpu_i/w_R_f_d_pcplus
add wave -noupdate /tb_cpu/cpu_i/w_R_f_d_alu_out
add wave -noupdate /tb_cpu/cpu_i/w_4_f_d_reg_wr_addr
add wave -noupdate /tb_cpu/cpu_i/w_R_e_f_alu_out
add wave -noupdate /tb_cpu/cpu_i/w_R_e_f_wr_data
add wave -noupdate /tb_cpu/cpu_i/w_4_e_f_reg_wr_addr
add wave -noupdate /tb_cpu/cpu_i/w_R_e_f_pc_branch
add wave -noupdate /tb_cpu/cpu_i/w_4_d_r_fwd_wr_addr_from_cu
add wave -noupdate /tb_cpu/cpu_i/w_4_d_r_rd1_addr_from_cu
add wave -noupdate /tb_cpu/cpu_i/w_2_d_r_fwd_wr_sel
add wave -noupdate /tb_cpu/cpu_i/w_5_d_r_alu_control
add wave -noupdate /tb_cpu/cpu_i/w_4_d_r_rd1_addr1
add wave -noupdate /tb_cpu/cpu_i/w_4_d_r_rd2_addr1
add wave -noupdate /tb_cpu/cpu_i/w_4_d_r_rd2_addr2
add wave -noupdate /tb_cpu/cpu_i/w_R_d_r_wr_data
add wave -noupdate /tb_cpu/cpu_i/w_4_d_r_reg_wr_addr
add wave -noupdate /tb_cpu/cpu_i/w_4_d_r_fwd_wr_addr1
add wave -noupdate /tb_cpu/cpu_i/w_4_d_r_fwd_wr_addr2
add wave -noupdate /tb_cpu/cpu_i/w_11_d_r_imm
add wave -noupdate /tb_cpu/cpu_i/w_R_d_r_pcplus
add wave -noupdate /tb_cpu/cpu_i/w_5_r_e_alu_control
add wave -noupdate /tb_cpu/cpu_i/w_R_r_e_rd1_data
add wave -noupdate /tb_cpu/cpu_i/w_R_r_e_rd2_data
add wave -noupdate /tb_cpu/cpu_i/w_4_r_e_reg_wr_addr
add wave -noupdate /tb_cpu/cpu_i/w_R_r_e_sign_imm
add wave -noupdate /tb_cpu/cpu_i/w_R_r_e_pcplus
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {3943 ps} 1} {{Cursor 2} {2883959 ps} 1} {{Cursor 3} {18041 ps} 1}
quietly wave cursor active 3
configure wave -namecolwidth 383
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {49224 ps}
